server:
  port: 8040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: fastcode
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  client:
    config:
      user-service:
        url: http://localhost:8090/api/v1/users
      product-service:
        url: http://localhost:8050/api/v1/products


app:
  fastcode:
    jwt:
      jwt-secret: byH8Rd8FgnjKlxlNXY5vyn3oIkV+KY2dida4OYZFaCFyB3CI06ERaWBMg1eRZmMEqeofjILhDeJA2ag66MQ/Eg==
      app-name: ecommerce
      expired: 3600000  # dalam milidetik (1 jam)
